services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-order-service
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=order_service
    volumes:
      - mysql-order-data:/var/lib/mysql

volumes:
  mysql-order-data: